### ISSUE TITLE
Slot and Track

### ISSUE THREAD

**Issue by ajuchacko91** [spatie/attended.io#44]
I have emailed some of you asking what is Slot and Track? I have not got a reply 
so is there anyone who would care to answer that
@freekmurze @rubenvanassche @pedroborges @willemvb @sebastiandedeyne

**Comment by freekmurze** [comment]
Please note that we don't provide support for this work in progress, so please don't mention groups of people.

 An event can have multiple tracks. A track can have multiple slots.

**Comment by ajuchacko91** [comment]
It's Okay!
